using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Symphony.Portal.Web.Data;
using Symphony.Portal.Web.Models;

namespace Symphony.Portal.Web.Controllers.Admin
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [Route("Admin/[controller]/[action]")]
    public class EntranceExamsController : Controller
    {
        private readonly AppDbContext _context;

        public EntranceExamsController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.EntranceExams.OrderByDescending(e => e.ExamDate).ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EntranceExam entranceExam)
        {
            if (ModelState.IsValid)
            {
                // Ensure ID is generated if not provided (though EF Core usually handles string IDs, 
                // for ULID/CUID we might need valid values if not auto-generated by DB)
                // For now assuming user input or ULID logic elsewhere, or simple string entry.
                // If it's a simple string, we let it be. 
                // However, for best practice with "string keys", we should generate one if empty.
                if (string.IsNullOrEmpty(entranceExam.Id))
                {
                    entranceExam.Id = Guid.NewGuid().ToString(); // Temporary UUID usage
                }

                _context.Add(entranceExam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(entranceExam);
        }

        // GET: Admin/EntranceExams/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null) return NotFound();

            var exam = await _context.EntranceExams.FindAsync(id);
            if (exam == null) return NotFound();

            return View(exam);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, EntranceExam entranceExam)
        {
            if (id != entranceExam.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entranceExam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExamExists(entranceExam.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(entranceExam);
        }

        private bool ExamExists(string id)
        {
            return _context.EntranceExams.Any(e => e.Id == id);
        }
    }
}
